# Generated by Django 3.2 on 2021-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('otp', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
