# Generated by Django 3.2 on 2021-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0002_alter_taskmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
