# Generated by Django 3.2 on 2021-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0003_alter_taskmodel_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
